/* GENERATED by tools/mkfont.py - do not edit. */
#ifndef EA_FONTS_GEN_H
#define EA_FONTS_GEN_H
#include "gfx.h"

extern const ea_font EA_FONT_TITLE;
extern const ea_font EA_FONT_PANEL;
extern const ea_font EA_FONT_LCD;
extern const ea_font EA_FONT_TRACK;
extern const ea_font EA_FONT_IND;
extern const ea_font EA_FONT_BTN;
extern const ea_font EA_FONT_CTL;
extern const ea_font EA_FONT_SMALL;
extern const ea_font EA_FONT_SYM;
extern const ea_font EA_FONT_LINK;
extern const ea_font EA_FONT_BIG;

#endif
