#!/usr/bin/env python3
"""Rasterize EasyAmp's two TTFs into C glyph atlases for the retro client.

The Win9x/XP client draws every pixel itself, so text is pre-rendered here:
each face is a fixed pixel size with 8-bit coverage per glyph, plus an
optional pre-blurred "glow" layer (the CSS text-shadow halo of the GTK app)
so a 400 MHz machine never has to blur anything at runtime.

Usage: tools/mkfont.py            (writes src/fonts_gen.c + src/fonts_gen.h)
"""
from __future__ import annotations

import math
import os
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter

HERE = os.path.dirname(os.path.abspath(__file__))
FONTS = os.path.join(HERE, "..", "..", "easyamp", "fonts")
PIXELIFY = os.path.join(FONTS, "PixelifySans.ttf")
DSEG7 = os.path.join(FONTS, "DSEG7Classic-Regular.ttf")
# The Plex link code is typed by a human into a phone, so it must be
# unambiguous - and Pixelify Sans draws 2/Z, 5/S, 8/B and 0/O as the SAME
# shape (6/G nearly). DejaVu Sans Mono Bold has a slashed zero and distinct
# forms for every one of those pairs. Bitstream Vera licence: free to embed.
DEJAVU_MONO_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"

ASCII = "".join(chr(c) for c in range(32, 127))

# name, ttf, px size, weight (variable axis) or None, glow [(sigma, opacity)], charset
FACES = [
    ("TITLE", PIXELIFY, 15, 700, [], ASCII),
    ("PANEL", PIXELIFY, 13, 700, [], ASCII),
    ("LCD",   PIXELIFY, 15, 400, [(4.0, 0.80)], ASCII),
    ("TRACK", PIXELIFY, 14, 400, [(2.0, 0.40)], ASCII),
    ("IND",   PIXELIFY, 10, 400, [(3.0, 0.90)], ASCII),
    ("BTN",   PIXELIFY, 10, 700, [], ASCII),
    ("CTL",   PIXELIFY, 10, 400, [(2.5, 0.50)], ASCII),
    ("SMALL", PIXELIFY, 10, 400, [], ASCII),
    ("SYM",   PIXELIFY, 16, 700, [], "+-x"),
    ("CODE",  DEJAVU_MONO_BOLD, 32, None, [(4.0, 0.85)], "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-"),
    ("BIG",   DSEG7,    32, None, [(5.0, 0.90), (1.3, 1.0)], "0123456789:-. "),
]


def load(ttf, size, weight):
    f = ImageFont.truetype(ttf, size)
    if weight is not None:
        f.set_variation_by_axes([weight])
    return f


def render_glyph(font, ch):
    """Return (coverage array, xoff, yoff, advance); offsets are from the
    pen position on the baseline to the bitmap's top-left."""
    adv = int(round(font.getlength(ch)))
    l, t, r, b = font.getbbox(ch, anchor="ls")
    w, h = r - l, b - t
    if w <= 0 or h <= 0:
        return np.zeros((0, 0), np.uint8), 0, 0, adv
    img = Image.new("L", (w + 2, h + 2), 0)
    ImageDraw.Draw(img).text((1 - l, 1 - t), ch, font=font, fill=255, anchor="ls")
    a = np.asarray(img, dtype=np.uint8)
    ys, xs = np.nonzero(a)
    if len(ys) == 0:
        return np.zeros((0, 0), np.uint8), 0, 0, adv
    y0, y1, x0, x1 = ys.min(), ys.max() + 1, xs.min(), xs.max() + 1
    return a[y0:y1, x0:x1].copy(), l - 1 + x0, t - 1 + y0, adv


def glow_layer(cov, layers):
    pad = int(math.ceil(3 * max(s for s, _ in layers)))
    big = np.pad(cov.astype(np.float32) / 255.0, pad)
    inv = np.ones_like(big)
    for sigma, opacity in layers:
        inv *= 1.0 - np.clip(gaussian_filter(big, sigma) * opacity, 0, 1)
    out = np.clip((1.0 - inv) * 255.0 + 0.5, 0, 255).astype(np.uint8)
    out[out < 3] = 0
    ys, xs = np.nonzero(out)
    if len(ys) == 0:
        return np.zeros((0, 0), np.uint8), 0, 0
    y0, y1, x0, x1 = ys.min(), ys.max() + 1, xs.min(), xs.max() + 1
    return out[y0:y1, x0:x1].copy(), x0 - pad, y0 - pad


def main():
    out_c = os.path.join(HERE, "..", "src", "fonts_gen.c")
    out_h = os.path.join(HERE, "..", "src", "fonts_gen.h")
    c = ["/* GENERATED by tools/mkfont.py - do not edit. */",
         '#include "gfx.h"', ""]
    h = ["/* GENERATED by tools/mkfont.py - do not edit. */",
         "#ifndef EA_FONTS_GEN_H", "#define EA_FONTS_GEN_H", '#include "gfx.h"', ""]
    total = 0
    for name, ttf, size, weight, glow, charset in FACES:
        font = load(ttf, size, weight)
        ascent, descent = font.getmetrics()
        blob = bytearray()
        rows = []
        for code in range(32, 127):
            ch = chr(code)
            if ch not in charset:
                rows.append("{0,0,0,0,0,0, 0,0,0,0,0}")
                continue
            cov, xo, yo, adv = render_glyph(font, ch)
            off = len(blob)
            blob += cov.tobytes()
            gw = gh = gxo = gyo = goff = 0
            if glow and cov.size:
                g, dx, dy = glow_layer(cov, glow)
                gh, gw = g.shape if g.size else (0, 0)
                gxo, gyo, goff = xo + dx, yo + dy, len(blob)
                blob += g.tobytes()
            hh, ww = cov.shape if cov.size else (0, 0)
            rows.append(f"{{{ww},{hh},{xo},{yo},{adv},{off}, {gw},{gh},{gxo},{gyo},{goff}}}")
        total += len(blob)
        c.append(f"static const unsigned char {name}_data[{max(len(blob),1)}] = {{")
        for i in range(0, len(blob), 32):
            c.append(",".join(str(b) for b in blob[i:i + 32]) + ",")
        if not blob:
            c.append("0")
        c.append("};")
        c.append(f"static const ea_glyph {name}_glyphs[95] = {{")
        c.append(",\n".join(rows))
        c.append("};")
        c.append(f"const ea_font EA_FONT_{name} = {{ {size}, {ascent}, {descent}, "
                 f"{1 if glow else 0}, {name}_glyphs, {name}_data }};")
        c.append("")
        h.append(f"extern const ea_font EA_FONT_{name};")
    h += ["", "#endif"]
    open(out_c, "w").write("\n".join(c) + "\n")
    open(out_h, "w").write("\n".join(h) + "\n")
    print(f"{len(FACES)} faces, {total/1024:.0f} KB of glyph data")


if __name__ == "__main__":
    sys.exit(main())
